In [1]:
import numpy as np
np.__version__

'1.18.5'

In [2]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [3]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [4]:
# multi-dimensional array that numpy supports
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
# Creating a 1X5 matrix of random values
np.random.random((1, 5))

array([[0.8790245 , 0.89589302, 0.11400251, 0.82694881, 0.07874806]])

In [8]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.23615093,  1.0573947 , -1.18536814],
       [ 0.2989824 ,  1.38722083, -1.00780808],
       [ 1.38333581,  1.00198394,  1.33793743]])

In [9]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 6, 3],
       [7, 7, 0],
       [4, 7, 2]])

In [10]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

In [22]:
''' NumPy Array Attributes '''
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print()
print("dtype:", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60

dtype: int64


In [32]:
''' Multi-dimensional array slicing '''
print(x2)
print()
x2[:2, :3]
print()
x2[:, ::2] # all rows, every other column
print()
x2[::-1, ::-1] # reversing subarray elements

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]





array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [47]:
''' Reshaping of Arrays '''
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

# reshape by using newaxis
x = np.array([1, 2, 3])
x

# row vector via reshape
x.reshape((1, 3))

# row vector via newaxis
x[np.newaxis, :]

# column vector via reshape
x.reshape((3, 1))

# column vector via newaxis
x[:, np.newaxis]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1],
       [2],
       [3]])

In [58]:
''' Array concatenation and splitting '''
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
 [6, 5, 4]])
y = np.array([[99],
            [99]])

# concatenate along the first axis
np.concatenate([grid, grid])

# concatenate along the second axis
np.concatenate([grid, grid], axis = 1)

'''For working with arrays of mixed dimensions, it can be clearer to use the np.vstack
(vertical stack) and np.hstack (horizontal stack) functions:'''

# vertically stack the arrays
np.vstack([x, grid])

# horizontal stack
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [63]:
''' Splitting of arrays '''
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

grid = np.arange(16).reshape((4, 4))
grid

''' Notice that N split points lead to N + 1 subarrays. The related functions np.hsplit
and np.vsplit are similar: '''
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

left, right = np.hsplit(grid, [2])
print(left)
print(right)

[1 2 3] [99 99] [3 2 1]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
